# Generated by Django 4.2.5 on 2023-09-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_preferseatrow_alter_seatsavailability_prefer_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatsavailability',
            name='prefer_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferable_row', to='api.preferseatrow'),
        ),
        migrations.AlterField(
            model_name='seatsavailability',
            name='prefer_seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferable_seat', to='api.preferseatrow'),
        ),
    ]
