# Generated by Django 4.2.5 on 2023-09-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_preferseatrow_preferseat_prefer_row_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreferSeat',
        ),
        migrations.RenameField(
            model_name='busavailability',
            old_name='from_city',
            new_name='departure_city',
        ),
        migrations.RenameField(
            model_name='busavailability',
            old_name='to_city',
            new_name='destination_city',
        ),
    ]
