# Generated by Django 4.2.5 on 2023-09-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_seatsavailability_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatsavailability',
            name='prefer_seat',
        ),
        migrations.AlterField(
            model_name='seatsavailability',
            name='prefer_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.preferseatrow'),
        ),
    ]
