# Generated by Django 4.2.5 on 2023-09-06 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_seatsavailability_seat_preferseatrow_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferseatrow',
            name='seat_number',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferseatrow',
            name='total_pax',
            field=models.IntegerField(default=4345, validators=[django.core.validators.MaxValueValidator(limit_value=2)]),
            preserve_default=False,
        ),
    ]
