# Generated by Django 4.2.5 on 2023-09-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_preferseatrow_seat_number_preferseatrow_total_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferseatrow',
            name='total_pax',
            field=models.IntegerField(),
        ),
    ]
