# Generated by Django 4.2.5 on 2023-09-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_preferseatrow_total_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatsavailability',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='preferseatrow',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
