# Generated by Django 4.2.5 on 2023-09-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_seatsavailability_prefer_row_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferseatrow',
            name='total_pax',
        ),
    ]
