# Generated by Django 4.2.5 on 2023-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_preferseatrow_total_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferseatrow',
            name='prefer_row',
            field=models.CharField(choices=[('Front', 'Front'), ('Center', 'Center'), ('Back', 'Back')], max_length=10),
        ),
        migrations.AlterField(
            model_name='preferseatrow',
            name='prefer_seat',
            field=models.CharField(choices=[('Window', 'Window'), ('Aisle', 'Aisle')], max_length=10),
        ),
    ]
