# Generated by Django 4.2.5 on 2023-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_preferseatrow_prefer_row_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferseatrow',
            old_name='is_booked',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='preferseatrow',
            name='total_pax',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferseatrow',
            name='prefer_row',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preferseatrow',
            name='prefer_seat',
            field=models.CharField(max_length=10),
        ),
    ]
