# Generated by Django 4.2.5 on 2023-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_is_booked_preferseatrow_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferseatrow',
            name='total_pax',
            field=models.IntegerField(null=True),
        ),
    ]
