# Generated by Django 4.2.5 on 2023-09-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_preferseatrow_total_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferseatrow',
            name='total_pax',
        ),
    ]
