# Generated by Django 4.2.5 on 2023-09-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_preferseatrow_seat_preferseatrow_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferseatrow',
            name='bus',
        ),
        migrations.AddField(
            model_name='preferseatrow',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seatsavailability'),
        ),
    ]
