# Generated by Django 4.2.5 on 2023-09-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_preferseatrow_bus_preferseatrow_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferseatrow',
            old_name='is_available',
            new_name='is_booked',
        ),
    ]
